server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://adminpage-rds.chw1s814wa0k.ap-northeast-2.rds.amazonaws.com:3306/adminpage?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: hyeonw777
    password: hyeonw7771234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    '[org.springframework.boot.web]': INFO